services:
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: laravel
    volumes:
      - ./backend:/var/www/html:cached
    networks:
      - app_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app_network

  db:
    image: postgres:18-alpine
    container_name: laravel_db
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge